### ISSUE TITLE
any possibility for an examples directory?

### ISSUE THREAD

**Issue by FishmanL** [opendifferentialprivacy/whitenoise-core-python#22]
docs are kinda unclear

**Comment by raprasad** [comment]
@FishmanL: 
  We'll work on making it clearer.  There are samples available here: https://github.com/opendifferentialprivacy/whitenoise-samples/tree/master/analysis

**Comment by FishmanL** [comment]
Hmm, aight, is there any code for 'ensure total epsilon is below some value'?

**Comment by Shoeboxam** [comment]
Given an example script like this:

```python
income_edges = list(range(0, 100_000, 10_000))

with wn.Analysis() as analysis:
    data = wn.Dataset(path=TEST_CSV_PATH, column_names=test_csv_names)
    income = wn.to_int(data['income'], lower=0, upper=0)

    for i in range(2):
        income_histogram = wn.dp_histogram(
            income,
            edges=income_edges,
            privacy_usage={'epsilon': 0.5}
```

You can view the overall privacy usage for the analysis like this:
```python
print(analysis.privacy_usage)
```

You can also check that the epsilon parameter in particular over the entire analysis is less than some budgeted value:
```python
print(analysis.privacy_usage.approximate.epsilon < budget)
```

More documentation and examples are necessary. In addition to the notebooks linked above, we need to expand and potentially convert some tests into more thorough examples.
https://github.com/opendifferentialprivacy/whitenoise-core-python/tree/develop/tests

**Comment by raprasad** [comment]
@FishmanL ^^

**Comment by FishmanL** [comment]
hmm, ok, but there's nothing native for 'clamp privacy usage to some total epsilon'?

**Comment by FishmanL** [comment]
Thanks

**Comment by ctcovington** [comment]
> hmm, ok, but there's nothing native for 'clamp privacy usage to some total epsilon'?

At this point, that's correct.
