### ISSUE TITLE
what does the flow for adding new components look like?

### ISSUE THREAD

**Issue by FishmanL** [opendifferentialprivacy/whitenoise-core-python#23]
it seems like it's 'modify components, then modify the rust validator and rust runtime'?

**Comment by Shoeboxam** [comment]
There is a contributing.md file here for core (directly relevant to your question):
https://github.com/opendifferentialprivacy/whitenoise-core/blob/develop/contributing.md

And a contributing.md file here for the bindings (tangentially relevant, but useful):
https://github.com/opendifferentialprivacy/whitenoise-core-python/blob/develop/contributing.md
