### ISSUE TITLE
remove/add deprecation warning to older python docs

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core-python#73]
Add a deprecation warning to these docs or take them down:
  - https://opendp.github.io/smartnoise-core-python/
---

- originally from #71

**Comment by pdurbin** [comment]
@raprasad and met yesterday and decided to effectively take them down by redirecting them.

This was done in 8e7acaa so that now https://opendp.github.io/smartnoise-core-python/ redirects to https://old-docs.smartnoise.org (a new site built from https://github.com/opendp/old-docs.smartnoise.org ).
